### ISSUE TITLE
todo: update _act_overview

### ISSUE THREAD

**Issue by chausch** [ppooll-dev/ppooll#9]
update _act_overview

- [x] classify new and/or changed acts
- [x] new column: "multichannel" or "mc-ready" or similar
- [x] add description for acts that are missing one

maybe: put act overview cellblock contents in external file for easier updateability
